export const GET_CARS_REQUEST = "GET_CARS_REQUEST";
export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS";
export const GET_CARS_FAILURE = "GET_CARS_FAILURE";

export const GET_CAR_BY_ID_REQUEST = "GET_CAR_BY_ID_REQUEST";
export const GET_CAR_BY_ID_REQUEST_SUCCESS = "GET_CAR_BY_ID_REQUEST_SUCCESS";
export const GET_CAR_BY_ID_REQUEST_FAILURE = "GET_CAR_BY_ID_REQUEST_FAILURE";

export const BOOKING_CAR_REQUEST = "BOOKING_CAR_REQUEST";
export const BOOKING_CAR_SUCCESS = "BOOKING_CAR_SUCCESS";
export const BOOKING_CAR_FAILURE = "BOOKING_CAR_FAILURE";