export const GET_CARS_REQUEST = "GET_CARS_REQUEST";
export const GET_CARS_SUCCESS = "GET_CARS_SUCCESS";
export const GET_CARS_FAILURE = "GET_CARS_FAILURE";

export const GET_CAR_BY_ID_REQUEST = "GET_CAR_BY_ID_REQUEST";
export const GET_CAR_BY_ID_REQUEST_SUCCESS = "GET_CAR_BY_ID_REQUEST_SUCCESS";
export const GET_CAR_BY_ID_REQUEST_FAILURE = "GET_CAR_BY_ID_REQUEST_FAILURE";

export const CREATE_CAR_REQUEST = "CREATE_CAR_REQUEST";
export const CREATE_CAR_SUCCESS = "CREATE_CAR_SUCCESS";
export const CREATE_CAR_FAILURE = "CREATE_CAR_FAILURE";

export const UPDATE_CAR_REQUEST = "UPDATE_CAR_REQUEST";
export const UPDATE_CAR_SUCCESS = "UPDATE_CAR_SUCCESS";
export const UPDATE_CAR_FAILURE = "UPDATE_CAR_FAILURE";

export const DELETE_CAR = "DELETE_CAR";
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const DELETE_CAR_FAILURE = "DELETE_CAR_FAILURE";

export const GET_CAR_BY_ID = "GET_CAR_BY_ID";
export const GET_CAR_BY_ID_SUCCESS = "GET_CAR_BY_ID_SUCCESS";
export const GET_CAR_BY_ID_FAILURE = "GET_CAR_BY_ID_FAILURE";

